### ISSUE TITLE
Prime program: Optimize Prime Checking Logic in Serial Primes Function

### ISSUE THREAD

**Issue by tommasocerruti** [xrdimmm/Parallel_Programming_Benchmarks#1]
The current prime checking logic in the serial_primes function can be optimized by skipping even numbers and using the fact that any non-prime number has a factor less than or equal to its square root.

**Comment by tommasocerruti** [comment]
Suggested Changes:

	1.	Modify the loop to start checking from 3 and increment by 2 to skip even numbers.
	2.	Change the termination condition of the inner loop to divisor * divisor <= num instead of divisor <= quotient.

**Comment by xrdimmm** [comment]
Linear code is not optimized in order the only thing changing between linear and parallel version visually to be the open-MP directives.
