### ISSUE TITLE
Prime program: Ensure Proper Memory Management

### ISSUE THREAD

**Issue by tommasocerruti** [xrdimmm/Parallel_Programming_Benchmarks#2]
Ensure that all dynamically allocated memory is properly freed to prevent memory leaks. Review and optimize memory usage where necessary.

**Comment by tommasocerruti** [comment]
Suggested Changes:

	1.	Verify that all allocated memory is freed at the end of the functions.
	2.	Add error handling to check the success of memory allocations.

**Comment by xrdimmm** [comment]
Project is focused mainly on the open-MP operations
